import type { Metadata } from 'next'
import { Crimson_Pro } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const crimsonpro = Crimson_Pro({
  display: 'swap',
  fallback: ['sans-serif'],
  subsets: ['latin'],
  weight: ['300', '500']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={crimsonpro.className}>
        {children}
      </body>
    </html>
  )
}
