import type { Metadata } from 'next'
import { Crimson_Pro } from 'next/font/google'

import './globals.css'
import { cn } from '@/lib/utils'

const font = Crimson_Pro({
  fallback: ['sans-serif'],
  preload: true,
  subsets: ['latin'],
  weight: ['300', '500']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          font.className,
          'bg-primary flex h-screen items-center justify-center font-light text-muted text-2xl w-screen'
        )}
      >
        {children}
      </body>
    </html>
  )
}
